name: Deploy to lambda
on: [push]
jobs:
    deploy_source:
        name: build and deploy lambda
        strategy:
            matrix:
                node-version: [18.16.1]
        runs-on: ubuntu-latest
        env:
            MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
            PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
            PINECONE_INDEX: ${{ secrets.PINECONE_INDEX }}
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install
              run: |
                  npm install
              env:
                  CI: true
            - name: zip
              uses: montudor/action-zip@v0.1.0
              with:
                  args: zip -qq -r ./bundle.zip ./
            - name: default deploy
              uses: appleboy/lambda-action@master
              with:
                  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws_region: ${{ secrets.AWS_REGION }}
                  function_name: handleDocumentsForPinecone
                  zip_file: bundle.zip
